apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.fullname" . }}-secret
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
data:
  rpc-secret: {{ .Values.garage.rpcSecret | b64enc | quote }}
  {{- if .Values.garage.s3Credentials.accessKeyId }}
  s3-access-key-id: {{ .Values.garage.s3Credentials.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.garage.s3Credentials.secretAccessKey }}
  s3-secret-access-key: {{ .Values.garage.s3Credentials.secretAccessKey | b64enc | quote }}
  {{- end }}
